### PR TITLE
CommitWithMetadataSource

### PR DESCRIPTION
**Pull request by IgorFedchenko**
As a part of work on issue #36 , this PR implements `CommitWithMetadataSource`.

Pretty simple overload to used `CommittingSourceStage` with passing function to extract string metadata from consumed message right after this message was consumed.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Will merge once conflicts are fixed

**Comment by Aaronontheweb** [comment]
lol I'm sorry @IgorFedchenko - just merged your `SourceWithOffsetContext` PR and it looks like we have conflicts again

**Comment by IgorFedchenko** [comment]
@Aaronontheweb Yup, I was expecting this - you have no choice other that merge one PR and get conflicts in another :) Have resolved it right now

**Comment by IgorFedchenko** [comment]
@Aaronontheweb There is this `AtMostOnceSource` test that is failing from time to time. I thought that this was due to small timeout I set, but now I am debugging it and there is something wrong there. So I will fix it and push commit to make tests pass stable.

**Comment by IgorFedchenko** [comment]
I spent some time yesterday on failing AtMostOnceSource test, and still did not find the reason (or, to be more accurate, I did not find a way to fix this) - so created issue #66 for now. 

This test is not related to this PR anyway, and was randomly failing during several other PRs. I thought that was a timeout issue, but it is something more complicated. Will return to this later.

So this PR can be merged now.

**Comment by Aaronontheweb** [comment]
Sounds good

**Pull request merged**
